// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEtWWZJvsqKRJEOZ6DYAWTzM9a7EPiTA',
    appId: '1:434301581436:web:020512751ba2f6279e31f9',
    messagingSenderId: '434301581436',
    projectId: 'cepu-app',
    authDomain: 'cepu-app.firebaseapp.com',
    storageBucket: 'cepu-app.firebasestorage.app',
    measurementId: 'G-ZHFX7GGDYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkzgx3BSsAGFBYkpNnXM7KpLv3Ddp1W4',
    appId: '1:434301581436:android:47361723c2b9b7809e31f9',
    messagingSenderId: '434301581436',
    projectId: 'cepu-app',
    storageBucket: 'cepu-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEtWWZJvsqKRJEOZ6DYAWTzM9a7EPiTA',
    appId: '1:434301581436:web:6e71dfcf087abed19e31f9',
    messagingSenderId: '434301581436',
    projectId: 'cepu-app',
    authDomain: 'cepu-app.firebaseapp.com',
    storageBucket: 'cepu-app.firebasestorage.app',
    measurementId: 'G-X4HVMCC1S9',
  );
}
