// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2olnSBrqzr-i01vDd7lmjouUjzCI1sDQ',
    appId: '1:492728747946:web:3e9df82e23bc9c32200dd3',
    messagingSenderId: '492728747946',
    projectId: 'notes-913aa',
    authDomain: 'notes-913aa.firebaseapp.com',
    storageBucket: 'notes-913aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiTUXSmTFzakNLHF9OmzZtRtCOBp0FCSk',
    appId: '1:492728747946:android:45350ad3e8e3a855200dd3',
    messagingSenderId: '492728747946',
    projectId: 'notes-913aa',
    storageBucket: 'notes-913aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6sghsBSXdWEgpvFjbVbq-dNSkbgpEx4',
    appId: '1:492728747946:ios:e127d941cc73f708200dd3',
    messagingSenderId: '492728747946',
    projectId: 'notes-913aa',
    storageBucket: 'notes-913aa.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6sghsBSXdWEgpvFjbVbq-dNSkbgpEx4',
    appId: '1:492728747946:ios:e127d941cc73f708200dd3',
    messagingSenderId: '492728747946',
    projectId: 'notes-913aa',
    storageBucket: 'notes-913aa.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2olnSBrqzr-i01vDd7lmjouUjzCI1sDQ',
    appId: '1:492728747946:web:570210a1cf1aefdb200dd3',
    messagingSenderId: '492728747946',
    projectId: 'notes-913aa',
    authDomain: 'notes-913aa.firebaseapp.com',
    storageBucket: 'notes-913aa.firebasestorage.app',
  );

}